var courseMatrixArray = [
		{
			name: "Maxim Integrated Philippines",
			modal_id: "maxim_modal",
			description: "Lorem ipsum smart",
			booth: "2-12",
			logo: "maxim.png",
			ChE: "i",
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "e",
			MetE: false,
			EM: false
		},
		{
			name: "Del Monte Philippines, Inc.",
			modal_id: "delmonte_modal",
			description: "Lorem ipsum globe",
			booth: "2-14",
			logo: "delmonte.png",
			ChE: "e",
			CE: false,
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: false,
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Phoenix Petroleum",
			modal_id: "phoenix_modal",
			description: "Lorem ipsum sun",
			booth: "4-28 (Th)",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: false,
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "United Laboratories",
			modal_id: "united_modal",
			description: "Lorem ipsum call",
			booth: "4-8 (T/W)",
			ChE: 	"ei",
			CE: 	"ei",
			CoE: 	"ei",
			CS: 	"ei",
			EE: 	"ei",
			ECE: 	"ei",
			GE: 	"ei",
			IE: 	"ei",
			MatE: 	"ei",
			ME: 	"ei",
			MetE: 	"ei",
			EM: 	"ei",
		},
		{
			name: "Coca-Cola FEMSA Philippines, Inc.",
			modal_id: "cocacola_modal",
			description: "Lorem ipsum sun",
			booth: "4-6 (T/W)",
			ChE: "ei",
			CE: false,
			CoE: "ei",
			CS: "e",
			EE: false,
			ECE: "i",
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Nokia Networks",
			modal_id: "nokia_modal",
			description: "Lorem ipsum sun",
			booth: "2-11",
			logo: "nokia.jpg",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "PMFTC Inc.",
			modal_id: "PMFTC_modal",
			description: "Lorem ipsum sun",
			booth:"2-1",
			logo: "pmftc.jpg",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Trend Micro Inc.",
			modal_id: "trendmicro_modal",
			description: "Lorem ipsum sun",
			booth: "4-12 (W)",
			ChE: false,
			CE: false,
			CoE: "i",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "MERALCO",
			modal_id: "meralco_modal",
			description: "Lorem ipsum sun",
			booth: "1-9",
			logo: "meralco.png",
			ChE: false,
			CE: "ei",
			CoE: false,
			CS: false,
			EE: false,
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Makati Development Corporation",
			modal_id: "makatidev_modal",
			description: "Lorem ipsum sun",
			booth: "2-2",
			logo: "mdc.PNG",
			ChE: false,
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: "e",
			GE: "ei",
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "EEI Corporation",
			modal_id: "eei_modal",
			description: "Lorem ipsum sun",
			booth: "2-15",
			logo: "eei.jpg",
			ChE: false,
			CE: "ei",
			CoE: "e",
			CS: "e",
			EE: "ei",
			ECE: "e",
			GE: "e",
			IE: "e",
			MatE: "e",
			ME: "ei",
			MetE: "e",
			EM: "e"
		},
		{
			name: "Fluor",
			modal_id: "fluor_modal",
			description: "Lorem ipsum sun",
			booth: "2-7",
			logo: "fluor.jpg",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: false,
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: "ei",
			ME: "ei",
			MetE: "e",
			EM: false
		},
		{
			name: "IBM",
			modal_id: "ibm_modal",
			description: "Lorem ipsum sun",
			booth: "4-30 (T/W)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "e",
			ECE: "ei",
			GE: false,
			IE: "e",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "TERASYSTEM INC.",
			modal_id: "TERASYSTEM_modal",
			description: "Lorem ipsum sun",
			ChE: false,
			CE: false,
			CoE: "e",
			CS: "e",
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Globe Tel Inc",
			modal_id: "globe_modal",
			description: "Lorem ipsum sun",
			booth: "3-6",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: "e",
			ME: "i",
			MetE: false,
			EM: false
		},
		{
			name: "Buildworks Design and Engineering",
			modal_id: "buildworks_modal",
			description: "Lorem ipsum sun",
			booth: "2-8",
			logo: "buildworks.png",
			ChE: "ei",
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: "e",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Texas Instruments Philippines",
			modal_id: "texas_modal",
			description: "Lorem ipsum sun",
			booth: "2-5",
			logo: "ti.jpg",
			ChE: "ei",
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: false
		},
		{
			name: "PETRON CORPORATION",
			modal_id: "petron_modal",
			description: "Lorem ipsum sun",
			booth: "1-7",
			ChE: "ei",
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: false,
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "MOTOLITE",
			modal_id: "motolite_modal",
			description: "Lorem ipsum sun",
			booth: "4-3",
			ChE: "ei",
			CE: false,
			CoE: "e",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: false
		},
		{
			name: "First Gen Corporation",
			modal_id: "firstgen_modal",
			description: "Lorem ipsum sun",
			booth: "2-4",
			logo: "firstgen.png",
			ChE: "ei",
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: "ei",
			GE: "e",
			IE: "e",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "AES Philippines",
			modal_id: "aes_modal",
			description: "Lorem ipsum sun",
			booth: "3-1",
			logo: "AES.JPG",
			ChE: "ei",
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "e",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "SAMSUNG SEMPHIL",
			modal_id: "samsung_modal",
			description: "Lorem ipsum sun",
			booth: "4-13 (Th/F)",
			ChE: "e",
			CE: "e",
			CoE: false,
			CS: false,
			EE: "e",
			ECE: "e",
			GE: false,
			IE: "e",
			MatE: "ei",
			ME: "e",
			MetE: "ei",
			EM: false
		},
		{
			name: "Siemens, Inc.",
			modal_id: "siemens_modal",
			description: "Lorem ipsum sun",
			booth: "4-5 (T/W)",
			ChE: false,
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "FactSet Philippines Inc.",
			modal_id: "factset_modal",
			description: "Lorem ipsum sun",
			booth: "2-9",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "PNOC EXPLORATION CORPORATION",
			modal_id: "pnoc_modal",
			description: "Lorem ipsum sun",
			booth: "4-21 (T/W)",
			ChE: false,
			CE: "e",
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: "e",
			MatE: false,
			ME: "e",
			MetE: false,
			EM: "ei"
		},
		{
			name: "Lafarge Republic",
			modal_id: "pnoc_modal",
			description: "Lorem ipsum sun",
			booth: "1-6",
			ChE: "ei",
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "e",
			ECE: false,
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: "ei"
		},
		{
			name: "Pointwest",
			modal_id: "pointwest_modal",
			description: "Lorem ipsum sun",
			booth: "2-3",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: "e",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Shell",
			modal_id: "shell_modal",
			description: "Lorem ipsum sun",
			booth: "2-13/6-2",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: "ei",
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: "ei"
		},
		{
			name: "Indra Philippines, Inc.",
			modal_id: "indra_modal",
			description: "Lorem ipsum sun",
			booth: "4-4 (T/W)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "ROHM LSI Design Philippines, Inc.",
			modal_id: "rohm_modal",
			description: "Lorem ipsum sun",
			booth: "6-1",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Jollibee Worldwide Services",
			modal_id: "jollibee_modal",
			description: "Lorem ipsum sun",
			booth: "1-1",
			logo: "jws.png",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Kooapps Philippines Corporation",
			modal_id: "kooapps_modal",
			description: "Lorem ipsum sun",
			booth: "4-29 (F)",
			ChE: false,
			CE: false,
			CoE: false,
			CS: "ei",
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Skillshot Labs",
			modal_id: "skillshot_modal",
			description: "Lorem ipsum sun",
			booth: "1-3",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Manila North Harbour Port, Inc.",
			modal_id: "manilanorth_modal",
			description: "Lorem ipsum sun",
			booth: "4-1",
			ChE: false,
			CE: false,
			CoE: false,
			CS: false,
			EE: false,
			ECE: false,
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "e",
			MetE: false,
			EM: false
		},
		{
			name: "Accenture, Inc",
			modal_id: "accenture_modal",
			description: "Lorem ipsum sun",
			booth: "2-10",
			logo: "accenture.png",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Clinic+",
			modal_id: "clinic_modal",
			description: "Lorem ipsum sun",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Toyota Motor Philippines",
			modal_id: "toyota_modal",
			description: "Lorem ipsum sun",
			ChE: "i",
			CE: false,
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Hewlett-Packard",
			modal_id: "hp_modal",
			description: "Lorem ipsum sun",
			booth: "2-6",
			logo: "hp.png",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "RCBC",
			modal_id: "rcbc_modal",
			description: "Lorem ipsum sun",
			booth: "4-9 (T)",
			ChE: false,
			CE: false,
			CoE: false,
			CS: false,
			EE: false,
			ECE: false,
			GE: false,
			IE: "e",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Aboitiz Power Corporation",
			modal_id: "aboitiz_modal",
			description: "Lorem ipsum sun",
			logo: "Aboitiz.jpg",
			booth: "3-2",
			ChE: "ei",
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: "ei",
			GE: "ei",
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Samsung Electronics Philippines Corporation",
			modal_id: "samsung_modal",
			description: "Lorem ipsum sun",
			booth: "4-24 (T)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Seven Seven Global Services, Inc.",
			modal_id: "sevenseven_modal",
			description: "Lorem ipsum sun",
			booth: "4-6 (Th/F)",
			ChE: false,
			CE: "e",
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "e",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Glyphstudios, Inc.",
			modal_id: "glyphstudios_modal",
			description: "Lorem ipsum sun",
			booth: "4-8 (Th/F)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Flying V",
			modal_id: "flyingv_modal",
			description: "Lorem ipsum sun",
			booth: "4-19 (T/W)",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: false,
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Beta Nanocoating Philippines Inc",
			modal_id: "betananocoating_modal",
			description: "Lorem ipsum sun",
			booth: "4-31 (T/W)",
			ChE: false,
			CE: false,
			CoE: false,
			CS: false,
			EE: false,
			ECE: false,
			GE: false,
			IE: "i",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: false
		},
		{
			name: "Deal Grocer",
			modal_id: "dealgrocer_modal",
			description: "Lorem ipsum sun",
			booth: "4-14 (T/W)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Misys Philippines",
			modal_id: "misys_modal",
			description: "Lorem ipsum sun",
			booth: "4-4 (Th/F)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: "e",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "TOTAL (Philippines) Corporation",
			modal_id: "totalcorp_modal",
			description: "Lorem ipsum sun",
			booth: "4-23 (T)",
			ChE: "e",
			CE: false,
			CoE: false,
			CS: false,
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: "e",
			MetE: false,
			EM: false
		},
		{
			name: "CGI",
			modal_id: "cgi_modal",
			description: "Lorem ipsum sun",
			booth: "4-25 (W)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "OpenText | GXS",
			modal_id: "opentext_modal",
			description: "Lorem ipsum sun",
			logo: "opentext.png",
			booth: "3-7",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "AUB",
			modal_id: "aub_modal",
			description: "Lorem ipsum sun",
			booth: "4-14 (Th/F)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Rokko & Associates, Inc.",
			modal_id: "rokko_modal",
			description: "Lorem ipsum sun",
			booth: "6-7",
			ChE: false,
			CE: false,
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Chiyoda Philippines Corporation",
			modal_id: "chiyoda_modal",
			description: "Lorem ipsum sun",
			booth: "4-32 (T/W)",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "i",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: false
		},
		{
			name: "Computer Professionals, Inc.",
			modal_id: "comppro_modal",
			description: "Lorem ipsum sun",
			ChE: false,
			CE: false,
			CoE: "e",
			CS: false,
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "J-SYS PHILS. INC.",
			modal_id: "jsysphil_modal",
			description: "Lorem ipsum sun",
			booth: "4-10 (T)",
			ChE: false,
			CE: false,
			CoE: "e",
			CS: "e",
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Unilever Philippines",
			modal_id: "unilever_modal",
			description: "Lorem ipsum sun",
			booth: "3-5",
			logo: "unilever.jpg",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: "ei",
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: "ei"
		},
		{
			name: "CEMEX",
			modal_id: "cemex_modal",
			description: "Lorem ipsum sun",
			booth: "4-2",
			ChE: "ei",
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: false,
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: false,
			MetE: false,
			EM: "i"
		},
		{
			name: "Careers at Ayala",
			modal_id: "ayala_modal",
			description: "Lorem ipsum sun",
			logo: "ayalagroup.png",
			booth: "3-8",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: "e",
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "AMKOR TECHNOLOGY PHILIPPINES, INC.",
			modal_id: "amkortech_modal",
			description: "Lorem ipsum sun",
			booth: "4-27 (F)",
			ChE: "ei",
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: "e",
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: false
		},
		{
			name: "Webcast Technologies, Inc.",
			modal_id: "webcasttech_modal",
			description: "Lorem ipsum sun",
			booth: "4-26 (W)",
			ChE: false,
			CE: false,
			CoE: false,
			CS: "i",
			EE: false,
			ECE: "i",
			GE: "e",
			IE: "e",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "LBP Service Corporation",
			modal_id: "lbp_modal",
			description: "Lorem ipsum sun",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: "ei",
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Orbium Inc",
			modal_id: "orbium_modal",
			description: "Lorem ipsum sun",
			booth: "4-26/4-29 (T)/4-33 (W)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "SunPower Phils Mfg. Ltd.",
			modal_id: "sunpower_modal",
			description: "Lorem ipsum sun",
			booth: "3-3",
			ChE: false,
			CE: false,
			CoE: false,
			CS: false,
			EE: "e",
			ECE: "e",
			GE: false,
			IE: "ei",
			MatE: "e",
			ME: "e",
			MetE: "e",
			EM: false
		},
		{
			name: "gemalto",
			modal_id: "gemalto_modal",
			description: "Lorem ipsum sun",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "INCUVENTURE",
			modal_id: "incuventure_modal",
			description: "Lorem ipsum sun",
			booth: "4-22 (T)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "e",
			GE: false,
			IE: "e",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Cognizant Technology Solutions",
			modal_id: "cognizant_modal",
			description: "Lorem ipsum sun",
			booth: "3-4/6-3",
			ChE: "e",
			CE: "e",
			CoE: "ei",
			CS: "ei",
			EE: "e",
			ECE: "ei",
			GE: "e",
			IE: "e",
			MatE: "e",
			ME: "e",
			MetE: "e",
			EM: "e"
		},
		{
			name: "Ecolab",
			modal_id: "ecolab_modal",
			description: "Lorem ipsum sun",
			booth: "4-20 (T/W)",
			ChE: "ei",
			CE: false,
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: false,
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "ERDT",
			modal_id: "erdt_modal",
			description: "Lorem ipsum sun",
			booth: "4-7 (T/W)",
			ChE: "e",
			CE: "e",
			CoE: "e",
			CS: "e",
			EE: "e",
			ECE: "e",
			GE: "e",
			IE: "e",
			MatE: "e",
			ME: "e",
			MetE: "e",
			EM: "e"
		},
		{
			name: "Greenfield Development Corporation",
			modal_id: "greenfield_modal",
			description: "Lorem ipsum sun",
			booth: "4-13 (T/W)/4-7 (Th/F)",
			ChE: false,
			CE: "ei",
			CoE: "ei",
			CS: "i",
			EE: "ei",
			ECE: "ei",
			GE: "ei",
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Mitchell Madison Group",
			modal_id: "mitchell_modal",
			description: "Lorem ipsum sun",
			ChE: "i",
			CE: "i",
			CoE: "i",
			CS: "i",
			EE: "ei",
			ECE: "i",
			GE: "i",
			IE: "ei",
			MatE: "i",
			ME: "i",
			MetE: "i",
			EM: "i"
		},
		{
			name: "Advanced World Systems, Inc.",
			modal_id: "advworld_modal",
			description: "Lorem ipsum sun",
			booth: "1-10",
			logo: "aws.png",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "e",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Dev-Touch Information Sytem Inc.",
			modal_id: "devtouch_modal",
			description: "Lorem ipsum sun",
			booth: "3-9",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Manly Plastics, Inc.",
			modal_id: "manlyplastics_modal",
			description: "Lorem ipsum sun",
			booth: "4-11 (W)",
			ChE: false,
			CE: false,
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: "e",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Philippine Geothermal Production Co. Inc.",
			modal_id: "philippinegeothermal_modal",
			description: "Lorem ipsum sun",
			booth: "4-16/4-17",
			ChE: "ei",
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "e",
			ECE: false,
			GE: false,
			IE: "i",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "KONE",
			modal_id: "kone_modal",
			description: "Lorem ipsum sun",
			booth: "1-8",
			ChE: false,
			CE: "ei",
			CoE: false,
			CS: false,
			EE: false,
			ECE: "e",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "San Miguel Corporation",
			modal_id: "sanmig_modal",
			description: "Lorem ipsum sun",
			booth: "1-2",
			ChE: "ei",
			CE: "ei",
			CoE: "i",
			CS: "i",
			EE: "i",
			ECE: "i",
			GE: "ei",
			IE: "ei",
			MatE: "i",
			ME: "ei",
			MetE: "ei",
			EM: "ei"
		},
		{
			name: "HGST Philippines Corporation",
			modal_id: "hgst_modal",
			description: "Lorem ipsum sun",
			booth: "4-27 (Th)",
			ChE: "ei",
			CE: false,
			CoE: "ei",
			CS: "e",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "e",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: false
		},
		{
			name: "Kalibrr",
			modal_id: "kalibrr_modal",
			description: "Lorem ipsum sun",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Nestle",
			modal_id: "nestle_modal",
			description: "Lorem ipsum sun",
			booth: "4-15",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: "ei",
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: "ei"
		},
		{
			name: "LAND BANK OF THE PHILIPPINES",
			modal_id: "landbank_modal",
			description: "Lorem ipsum sun",
			ChE: false,
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "e",
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: "e",
			MetE: false,
			EM: false
		},
		{
			name: "SMART COMMUNICATIONS",
			modal_id: "smartcomm_modal",
			description: "Lorem ipsum sun",
			booth: "6-11",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "LINE SEIKI",
			modal_id: "lineseiki_modal",
			description: "Lorem ipsum sun",
			ChE: false,
			CE: false,
			CoE: false,
			CS: false,
			EE: false,
			ECE: "e",
			GE: false,
			IE: false,
			MatE: false,
			ME: "e",
			MetE: false,
			EM: false
		},
		{
			name: "ARMSCOR",
			modal_id: "armscor_modal",
			description: "Lorem ipsum sun",
			booth: "1-4",
			ChE: "e",
			CE: false,
			CoE: false,
			CS: false,
			EE: false,
			ECE: "e",
			GE: false,
			IE: "ei",
			MatE: "e",
			ME: "ei",
			MetE: "e",
			EM: false
		},
		{
			name: "MAYNILAD WATER",
			modal_id: "maynilad_modal",
			description: "Lorem ipsum sun",
			booth: "4-12 (T)",
			ChE: "e",
			CE: "e",
			CoE: false,
			CS: false,
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "TIPCO",
			modal_id: "tipco_modal",
			description: "Lorem ipsum sun",
			booth: "4-11 (T)",
			ChE: "ei",
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "e",
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "DATEM Incorporated",
			modal_id: "datem_modal",
			description: "Lorem ipsum sun",
			booth: "1-5",
			ChE: false,
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: false,
			GE: "ei",
			IE: false,
			MatE: "e",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Waterproofing Contractor",
			modal_id: "waterproofing_modal",
			description: "Lorem ipsum sun",
			ChE: false,
			CE: "ei",
			CoE: false,
			CS: false,
			EE: false,
			ECE: false,
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "LARES",
			modal_id: "lares_modal",
			description: "Lorem ipsum sun",
			booth: "4-35/4-36",
			ChE: false,
			CE: "ei",
			CoE: "ei",
			CS: "ei",
			EE: "ei",
			ECE: "ei",
			GE: "ei",
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "NORTHERN CEMENT CORPORATION",
			modal_id: "northerncement_modal",
			description: "Lorem ipsum sun",
			booth: "6-8",
			ChE: "ei",
			CE: "ei",
			CoE: "i",
			CS: false,
			EE: "ei",
			ECE: "ei",
			GE: "ei",
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: "ei"
		},
		{
			name: "NXP Semiconductor Cabuyao Inc.",
			modal_id: "nxp_modal",
			description: "Lorem ipsum sun",
			ChE: "ei",
			CE: false,
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: "ei",
			GE: false,
			IE: "ei",
			MatE: "ei",
			ME: "ei",
			MetE: "ei",
			EM: false
		},
		{
			name: "Monde Nissin Corporation",
			modal_id: "monde_modal",
			description: "Lorem ipsum sun",
			booth: "4-9 (F)",
			ChE: "e",
			CE: false,
			CoE: false,
			CS: "e",
			EE: false,
			ECE: "e",
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
		{
			name: "Avaloq",
			modal_id: "avaloq_modal",
			description: "Lorem ipsum sun",
			booth: "4-28 (T/W)",
			ChE: false,
			CE: false,
			CoE: "ei",
			CS: "ei",
			EE: false,
			ECE: "i",
			GE: false,
			IE: false,
			MatE: false,
			ME: false,
			MetE: false,
			EM: false
		},
		{
			name: "Universal Robina Corporation",
			modal_id: "avaloq_modal",
			description: "Lorem ipsum sun",
			ChE: "ei",
			CE: "ei",
			CoE: false,
			CS: false,
			EE: "ei",
			ECE: false,
			GE: false,
			IE: "ei",
			MatE: false,
			ME: "ei",
			MetE: false,
			EM: false
		},
	];